# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000
#  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
#  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
#  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qqy update
    apt-get -qqy upgrade
    apt-get -qqy install make zip unzip

    apt-get -qqy install python3 python3-pip
    pip3 install --upgrade pip

    # Install dependencies
    pip3 install -r /vagrant/requirements.txt

    # Init and fill database with dummy entries
    python3 /vagrant/src/db_bookshelf.py
    python3 /vagrant/src/db_prefill.py

    echo "Done installing your virtual machine!"
  SHELL
end